Category: Error, Message: System.InvalidOperationException: No connection string named 'EntitiesGeneral' could be found in the application config file.
   en System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel()
   en System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   en System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   en Core.Erp.Data.General.tb_sis_Mensajes_sys_Data.Get_List_Mensajes_sys() en c:\Users\AROCA\Desktop\Proyectos GitHub\ERPUTAN\ERP_naturisa\ERP\Core.Erp.Data\General\tb_sis_Mensajes_sys_Data.cs:línea 49
Category: Error, Message: cargar_CuentaBanco - Core.Erp.Info.Log_Exception.DalException ---> System.Exception: System.InvalidOperationException: No connection string named 'EntitiesBanco' could be found in the application config file.
   en System.Data.Entity.Internal.LazyInternalConnection.get_ConnectionHasModel()
   en System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   en System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   en Core.Erp.Data.Bancos.ba_Banco_Cuenta_Data.Get_list_Banco_Cuenta(Int32 IdEmpres) en c:\Users\AROCA\Desktop\Proyectos GitHub\ERPUTAN\ERP_naturisa\ERP\Core.Erp.Data\Bancos\ba_Banco_Cuenta_Data.cs:línea 22
   en Core.Erp.Data.Bancos.ba_Banco_Cuenta_Data.Get_list_Banco_Cuenta(Int32 IdEmpres) en c:\Users\AROCA\Desktop\Proyectos GitHub\ERPUTAN\ERP_naturisa\ERP\Core.Erp.Data\Bancos\ba_Banco_Cuenta_Data.cs:línea 65
   en Core.Erp.Business.Bancos.ba_Banco_Cuenta_Bus.Get_list_Banco_Cuenta(Int32 IdEmpresa) en c:\Users\AROCA\Desktop\Proyectos GitHub\ERPUTAN\ERP_naturisa\ERP\Core.Erp.Bussines\Bancos\ba_Banco_Cuenta_Bus.cs:línea 53
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Core.Erp.Business.Bancos.ba_Banco_Cuenta_Bus.Get_list_Banco_Cuenta(Int32 IdEmpresa) en c:\Users\AROCA\Desktop\Proyectos GitHub\ERPUTAN\ERP_naturisa\ERP\Core.Erp.Bussines\Bancos\ba_Banco_Cuenta_Bus.cs:línea 58
   en Core.Erp.Winform.Controles.UCBa_Proceso_x_Banco.cargar_CuentaBanco() en c:\Users\AROCA\Desktop\Proyectos GitHub\ERPUTAN\ERP_naturisa\ERP\Core.Erp.Winform\Controles\UCBa_Proceso_x_Banco.cs:línea 63
